### ISSUE TITLE
Standardized Button + Header Components

### ISSUE THREAD

**Issue by sristii** [JumboCode/jumbocode.org-2024#2]
## 📝 Task Description 

Build a standardized **button component** & **header component** based on the [Figma](https://www.figma.com/design/5api4DeB6kUP6h7G6NGhNG/JumboCode?node-id=76-37&node-type=canvas&t=9xr8EegCZ2gUvVQP-0).

These components will be reused throughout the site! Please populate each page with the headers (there just won't be a navbar yet since that's someone else's ticket, so may get tedious navigating thru pages)

**Be sure to push & pull from the ` dev ` branch**

## ✅ Acceptance Criteria 

- [x] Is the button component reusable across different pages, accepting props for text, routing, and button color?
- [x] Is the header component reusable across different pages, accepting props for page title, and description?
- [x] Does the button navigate to the correct page on click?
- [x] Is there a proper hover effect for the button?
- [x] Is the styling for both components aligned with the design in Figma?

## 🔍 Subtask Breakdown
- **Button Component**:
  - Takes in `text` (string) and `route` (string) as props.
  - Navigate to the correct page on click.
  - Add support for additional props like styling (white/blue button) or icons if needed.
  
- **Header Component**:
  - Takes in `title` (string) and `description` (string) as props.
  - Properly styled according to Figma.

**Also, if you know of a better way to tackle this, DO IT UR WAY PLS, whatever is most intuitive to you**

## 💫  Recommended Approach

Start by building and styling the button component → move on to the header component → maybe make/populate pages with headers (and buttons if needed according to the design)

Make sure to utilize Dev Mode & Preview Mode in Figma to ensure your implementation matches the design. Making universal components helps make it possible for consistency across the app (++ points for abstraction yay!!)

## ✨ Resources ✨

- [Tailwind Button's](https://v1.tailwindcss.com/components/buttons)
- [Components in React](https://react.dev/learn/your-first-component)

**Comment by benborgers** [comment]
@sristii Just wanted to clarify! What do you mean by the header?

**Comment by sristii** [comment]
@benborgers 
<img width="350" alt="Screenshot 2024-12-22 at 10 58 19 PM" src="https://github.com/user-attachments/assets/9e331275-0048-4ad1-a748-a15e37762ce7" />
This part of the page(s)! If you look at the main pages (Home, About, Projects, Apply) they all follow the same format-ish (some have buttons, some don't)!

I'm also going to re-assign the navigation bar ticket to you since I think it'll go hand in hand/be easier to dev that all in one go!! lmk if u need any further clarification :P
